version: '3'
services:
  lhserver:
    build:
      context: .
      dockerfile: ./docker-server/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./lhci-data:/data
  client:
    build:
      context: .
      dockerfile: ./docker-client/Dockerfile
    depends_on:
      - lhserver
